### ISSUE TITLE
Car names

### ISSUE THREAD

**Issue by Ech0riath** [TanguyOrtegat/esx_jb_eden_garage2#35]
vehicle names don't appear

**Comment by TanguyOrtegat** [comment]
can you show me a screen any errors client / server sided ? becasue on my severr works great

**Comment by lord0o** [comment]
![image](https://user-images.githubusercontent.com/1349872/61600162-94a27700-ac05-11e9-9fb2-43f882e779bf.png)

I have 2 cars.
Fiat 595 
Porsche 911

The only car I can see in the car list on the garage is Fiat 959...I mean this because when I bought only the Fiat 959, i couldn't see it either... it shows only "Auto: Devolver" as a car
then it prompt me if i want to take out my car or rename it
![image](https://user-images.githubusercontent.com/1349872/61600185-c3205200-ac05-11e9-865a-e9fbaf12a247.png)

**Comment by lord0o** [comment]
Now i've bought a 3rd car, and this is what I see on the green marker menu

![image](https://user-images.githubusercontent.com/1349872/61600225-024ea300-ac06-11e9-8025-a4fab9b74ab7.png)

**Comment by TanguyOrtegat** [comment]
i ll look at it end august, i am on vacation now :)

**Comment by lord0o** [comment]
> 
> 
> i ll look at it end august, i am on vacation now :)

Oka! have a nice vacation! :)

**Comment by TanguyOrtegat** [comment]
still that issue ? because if  it doesn't show up carname it is maybe becasue add on car and you didn't give it any name :)
