### ISSUE TITLE
Job vehicle into civil garage

### ISSUE THREAD

**Issue by Rubylium** [TanguyOrtegat/esx_jb_eden_garage2#46]
Not really an issue but an request.
It will be very cool to see an option to **not** display job vehicle into civil garage.

For exemple if i buy my LSPD vehicle, i will also see the vehicle into all civil garage.

About the SQL fetchAll i tried doing `SELECT * FROM owned_vehicles WHERE owner = @identifier AND job IS NULL`, it work greate and do not display,job vehicles but i can not spawn the vehicles anymore.

Hope you understand me :)

**Comment by TanguyOrtegat** [comment]
there is no need for job column. script is already made so that it can handle society (job) vehicles. Instead on steam... in owner column you wil have police or ambulance or ... 

You just need to trugger these events:
https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/master/esx_jb_eden_garage2_cl.lua#L832

**Comment by TanguyOrtegat** [comment]
![image](https://user-images.githubusercontent.com/17274032/63697620-8d324700-c81d-11e9-9698-28cd96ad2038.png)
here you have an example ^^
